version: "3"

services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=admin
    healthcheck:
      test: "curl -f -s http://localhost"
    volumes:
      - ./config:/config
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.entrypoints=http"
      - "traefik.http.routers.librespeed.rule=Host(`librespeed.example.com`)"
      - "traefik.http.middlewares.librespeed-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.librespeed.middlewares=librespeed-https-redirect"
      - "traefik.http.routers.librespeed-secure.entrypoints=https"
      - "traefik.http.routers.librespeed-secure.rule=Host(`librespeed.example.com`)"
      - "traefik.http.routers.librespeed-secure.tls=true"
      - "traefik.http.routers.librespeed-secure.service=librespeed"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
