version: "3"

services:
  librespeed:
    image: ghcr.io/linuxserver/librespeed:latest
    container_name: librespeed
    restart: unless-stopped
    ports:
      - "8010:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - PASSWORD=admin
    healthcheck:
      test: "curl -f -s http://localhost"
    volumes:
      - ./config:/config
