version: "3"

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
      - ../docker-swag/config/etc:/le-ssl:ro
    command:
      - "--ssl"
      - "--sslcert=/le-ssl/letsencrypt/live/docker.example.com/cert.pem"
      - "--sslkey=/le-ssl/letsencrypt/live/docker.example.com/privkey.pem"
