version: "3"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
