version: "3"

services:
  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    restart: unless-stopped
    ports:
      - 19999:19999
    environment:
      - VIRTUALIZATION=kvm
    volumes:
      - /etc/group:/host/etc/group:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - ./cache:/var/cache/netdata
      - ./config:/etc/netdata
      - ./lib:/var/lib/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
