version: "3.8"

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    restart: unless-stopped
    volumes:
      - ./conf.yml:/app/public/conf.yml
    environment:
      - NODE_ENV=production
      - UID=1000
      - GID=1000
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      start_period: 1m
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashy.entrypoints=http"
      - "traefik.http.routers.dashy.rule=Host(`dashy.example.com`)"
      - "traefik.http.middlewares.dashy-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.dashy.middlewares=dashy-https-redirect"
      - "traefik.http.routers.dashy-secure.entrypoints=https"
      - "traefik.http.routers.dashy-secure.rule=Host(`dashy.example.com`)"
      - "traefik.http.routers.dashy-secure.tls=true"
      - "traefik.http.routers.dashy-secure.service=dashy"
      - "traefik.http.services.dashy.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
