version: "3"

services:
  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - ./influxdbv2:/root/.influxdbv2
      - ../docker-swag/config/etc:/le-ssl:ro
    ports:
      - 8086:8086
    environment:
      - INFLUXD_TLS_CERT=/le-ssl/letsencrypt/live/docker.example.com/cert.pem
      - INFLUXD_TLS_KEY=/le-ssl/letsencrypt/live/docker.example.com/privkey.pem
      - INFLUXD_REPORTING_DISABLED=true
    healthcheck:
      test: ["CMD", "influx", "ping", "--host", "https://localhost:8086", "--skip-verify"]
